### ISSUE TITLE
Calamari Using nimbus: cannot read properties of undefined (reading 'notFirstBlock')

### ISSUE THREAD

**Issue by zqhxuyuan** [AcalaNetwork/chopsticks#216]
yarn start:
```
TypeError: Cannot read properties of undefined (reading 'notFirstBlock')
    at newHeader (/Users/zqh/code/substrates/chopsticks/packages/chopsticks/src/blockchain/block-builder.ts:84:68)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async dryRunExtrinsic (/Users/zqh/code/substrates/chopsticks/packages/chopsticks/src/blockchain/block-builder.ts:218:18)
    at async Blockchain.dryRunExtrinsic (/Users/zqh/code/substrates/chopsticks/packages/chopsticks/src/blockchain/index.ts:184:37)
    at async dryRun (/Users/zqh/code/substrates/chopsticks/packages/chopsticks/src/dry-run.ts:14:36)
    at async Object.handler (/Users/zqh/code/substrates/chopsticks/packages/chopsticks/src/cli.ts:122:9)
```

run in dev mode, can open 8000 successful first, but after make a transfer transaction, error in terminal, and can't open 8000.
```
[17:20:17.129] TRACE (ws/97187): Subscription notification
    method: "author_extrinsicUpdate"
    subid: "8a8s3glt0yb"
    data: {
      "Ready": null
    }
[17:20:17.234] TRACE (executor/97187): taskRun
    wasm: "0x52bc537646db8e0528b52ffd00583c1a…271798f19320eca23b8a114d30c70901"
    calls: [
      [
        "AuraApi_slot_duration",
        []
      ]
    ]
    storage: []
    mockSignatureHost: false
    allowUnresolvedImports: false
[17:20:17.373] TRACE (executor/97187): taskResponse
    result: "0xe02e000000000000"
    storageDiff: []
[17:20:17.389] TRACE (layer/97187): RemoteStorageLayer get
    at: "0x79e168f619190c89659a0575bffd9749d4fa654df797afb0d2cdff2064c9eb17"
    key: "0x45323df7cc47150b3930e2666b0aa31390d171f8401887cf06fb43a732994c32"
TypeError: Cannot read properties of undefined (reading 'notFirstBlock')
    at newHeader (/Users/zqh/code/substrates/chopsticks/packages/chopsticks/src/blockchain/block-builder.ts:84:68)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at buildBlock (/Users/zqh/code/substrates/chopsticks/packages/chopsticks/src/blockchain/block-builder.ts:137:18)
    at TxPool.#buildBlock (/Users/zqh/code/substrates/chopsticks/packages/chopsticks/src/blockchain/txpool.ts:107:43)
    at TxPool.buildBlock (/Users/zqh/code/substrates/chopsticks/packages/chopsticks/src/blockchain/txpool.ts:87:5)
[ERROR] 17:20:17 TypeError: Cannot read properties of undefined (reading 'notFirstBlock')
```

**Comment by ermalkaleci** [comment]
can be fixed using hard-coded key

**Comment by ermalkaleci** [comment]
calamari not exposing randomness storage

**Comment by ermalkaleci** [comment]
> we don't have randomness pallet yet, is this PR cause the error: https://github.com/AcalaNetwork/chopsticks/pull/95/files#diff-41d4c269892acedcac86c6f536dc1154074629de2dfeba6491b0268a9d0e2dfd. What do you mean hard-coded key, what should I add to config file?

no, we need to update chopsticks

**Comment by ermalkaleci** [comment]
randomness reset now checks if it exists. I think now you need to provide some storage override to make nimbus works like https://github.com/AcalaNetwork/chopsticks/blob/master/configs/moonriver.yml

**Comment by ermalkaleci** [comment]
running just with endpoint will fail here https://github.com/PureStake/nimbus/blob/550d5377be7a40ea8bfd9f4964b9a1ef18c99fc4/pallets/author-inherent/src/lib.rs#L134
