### ISSUE TITLE
send signed tx without signature causing chopsticks to throw error

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/chopsticks#375]
it should handle such issue and not throw error

```
[05:06:49.314] ERROR (rpc-author/467): ExtrinsicFailed
    error: {
      "unknown": {
        "noUnsignedValidator": null
      }
    }
/home/runner/acalajs-examples/node_modules/@polkadot/types-create/cjs/create/type.js:54
        firstError = new Error(`createType(${type}):: ${error.message}`);
                     ^

Error: createType(ExtrinsicStatus):: Cannot map Enum JSON, unable to find 'unknown' in future, ready, broadcast, inblock, retracted, finalitytimeout, finalized, usurped, dropped, invalid
    at createTypeUnsafe (/home/runner/acalajs-examples/node_modules/@polkadot/types-create/cjs/create/type.js:54:22)
    at TypeRegistry.createTypeUnsafe (/home/runner/acalajs-examples/node_modules/@polkadot/types/cjs/create/registry.js:271:52)
    at RpcCore._formatOutput (/home/runner/acalajs-examples/node_modules/@polkadot/rpc-core/cjs/bundle.js:309:25)
    at RpcCore._formatResult (/home/runner/acalajs-examples/node_modules/@polkadot/rpc-core/cjs/bundle.js:147:20)
    at Object.update [as callback] (/home/runner/acalajs-examples/node_modules/@polkadot/rpc-core/cjs/bundle.js:238:48)
    at WsProvider.__internal__onSocketMessageSubscribe (/home/runner/acalajs-examples/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:170:25)
    at WsProvider.__internal__onSocketMessage (/home/runner/acalajs-examples/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:123:24)
    at callListener (/home/runner/acalajs-examples/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/runner/acalajs-examples/node_modules/ws/lib/event-target.js:209:9)
```

**Comment by qiweiii** [comment]
this error is thrown here: https://github.com/AcalaNetwork/chopsticks/blob/82aa8c8027e92705aecee241312f660762e85278/packages/core/src/blockchain/index.ts#L269

@xlc By ‘handle’ it, do you mean we should do some other checks in `validateExtrinsic` to validate unsigned extrinsics, so the `validity.isOk` will be true

**Comment by xlc** [comment]
No. It should fail, but gracefully. You can try send an unsigned tx on a normal RPC node and see what happened and mimic that. But we should never throw errors (without any catches) unless it is something shouldn't happen, like out of disk space.

**Comment by qiweiii** [comment]
I connected to localhost:8000, using currencies.transfer, then submit unsiged.

the error is thrown, but it's catched in here: https://github.com/AcalaNetwork/chopsticks/blob/02c4851a13eeeb195d69098ea06e309a50399e76/packages/chopsticks/src/rpc/substrate/author.ts#L57

So local rpc node it's not crashed, still running. How to mimic the case that it does not catch this error?

**Comment by xlc** [comment]
Actually the error is from polkadot.js connecting to chopsticks, not from chopsticks itself.

`Error: createType(ExtrinsicStatus):: Cannot map Enum JSON, unable to find 'unknown' in future, ready, broadcast, inblock, retracted, finalitytimeout, finalized, usurped, dropped, invalid`

So the RPC returned a response that's unrecognised by polkadot.js and crashed polkadot.js. The fix will be updating the error type to something can be handled by polkadot.js. Again, it should behave the same as a normal node.
