### ISSUE TITLE
`Object.hasOwn` is not a function

### ISSUE THREAD

**Issue by savudani8** [AcalaNetwork/chopsticks#56]
Getting this error on node v14.17.6, when I connect to the node with polkadot-apps:
```bash
(node:1360079) UnhandledPromiseRejectionWarning: TypeError: Object.hasOwn is not a function
    at WebSocket.<anonymous> (/.../chopsticks/src/server.ts:88:27)
    at WebSocket.emit (events.js:400:28)
    at Receiver.receiverOnMessage (/.../chopsticks/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.dataMessage (/.../chopsticks/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/.../chopsticks/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/.../chopsticks/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/.../chopsticks/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)

```

The command I ran is `yarn dev:acala` but I get this error regardles of how I start the node. Removing the `!Object.hasOwn(...)` check here fixes it for me: https://github.com/AcalaNetwork/chopsticks/blob/c3356546a0031f810367655f89c8d6a7f2dee868/src/server.ts#L88

**Comment by xlc** [comment]
We don't plan to support nodejs 14. Please use a recent version.
