### ISSUE TITLE
Chopsticks not compatible with Moonbeam RT260X Runtimes

### ISSUE THREAD

**Issue by albertov19** [AcalaNetwork/chopsticks#575]
Moonbeam-based networks upgraded to RT260X and now Chopsticks is not compatible with any of them.  For example, the error I get when I launch Chopsticks pointing to Moonbeam is:

```
npx @acala-network/chopsticks@latest -c moonbeam
```

Logs:

```
panicked at 'called `Result::unwrap()` on an `Err` value: VirtualMachine(UnresolvedFunctionImport { function: "ext_panic_handler_abort_on_panic_version_1", module_name: "env" })', src/task.rs:133:6

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (/home/purestake/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:729:19)
    at wasm://wasm/009743be:wasm-function[728]:0x12aaea
    at wasm://wasm/009743be:wasm-function[886]:0x13420c
    at wasm://wasm/009743be:wasm-function[802]:0x12eaca
    at wasm://wasm/009743be:wasm-function[105]:0xa92ae
    at wasm://wasm/009743be:wasm-function[355]:0x10e846
    at wasm://wasm/009743be:wasm-function[937]:0x134a9e
    at __wbg_adapter_46 (/home/purestake/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:407:10)
    at real (/home/purestake/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:391:22)
    at node:internal/process/task_queues:141:7



node:internal/event_target:777
  process.nextTick(() => { throw err; });
                           ^
Error [RuntimeError]: unreachable
    at wasm://wasm/009743be:wasm-function[728]:0x12ac13
    at wasm://wasm/009743be:wasm-function[886]:0x13420c
    at wasm://wasm/009743be:wasm-function[802]:0x12eaca
    at wasm://wasm/009743be:wasm-function[105]:0xa92ae
    at wasm://wasm/009743be:wasm-function[355]:0x10e846
    at wasm://wasm/009743be:wasm-function[937]:0x134a9e
    at __wbg_adapter_46 (/home/purestake/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:407:10)
    at real (/home/purestake/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:391:22)
    ```
    
    
    This is using Chopsticks version `0.9.3`

**Comment by albertov19** [comment]
It seems that with the flag `--allow-unresolved-imports true` it works :)

**Comment by wuzhong-zhu** [comment]
🙏🙏🙏wow cool! Thanks!!!

**Comment by albertov19** [comment]
@xlc @ermalkaleci It seems that `--allow-unresolved-imports true` does not work with the `xcm` feature of Chopsticks. Do you know any alternative?

**Comment by ermalkaleci** [comment]
#584

**Comment by ermalkaleci** [comment]
new beta will be released in a few minutes

**Comment by albertov19** [comment]
Thank you @ermalkaleci - I'll keep the issue open to ensure the compatibility issues are solved for Moonbeam-based networks

**Comment by ermalkaleci** [comment]
0.9.4-6 should work

**Comment by albertov19** [comment]
Hey @ermalkaleci it seems that is not working as expected with `"@acala-network/chopsticks": "0.9.4-6"
`:

```
npx @acala-network/chopsticks@latest xcm -r polkadot -p hydradx -p moonbeam
[11:43:25.858] INFO (905279): Loading config file https://raw.githubusercontent.com/AcalaNetwork/chopsticks/master/configs/hydradx.yml
Unable to map [u8; 32] to a lookup index
chopsticks xcm

XCM setup with relaychain and parachains

Options:
  -v, --version     Show version number                                [boolean]
  -h, --help        Show help                                          [boolean]
  -r, --relaychain  Relaychain config file path                         [string]
  -p, --parachain   Parachain config file path                [array] [required]

ZodError: [
  {
    "code": "unrecognized_keys",
    "keys": [
      "allow-unresolved-imports"
    ],
    "path": [],
    "message": "Unrecognized key(s) in object: 'allow-unresolved-imports'"
  }
]
    at Object.get error [as error] (/home/purestake/.npm/_npx/81ad9c881cb83600/node_modules/zod/lib/types.js:43:31)
    at ZodObject.parse (/home/purestake/.npm/_npx/81ad9c881cb83600/node_modules/zod/lib/types.js:143:22)
    at fetchConfig (/home/purestake/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks/dist/cjs/schema/index.js:99:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.handler (/home/purestake/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks/dist/cjs/cli.js:71:62) {
  issues: [
    {
      code: 'unrecognized_keys',
      keys: [Array],
      path: [],
      message: "Unrecognized key(s) in object: 'allow-unresolved-imports'"
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)]
}
[11:43:28.547] INFO (xcm/905279): HydraDX RPC listening on port 8000
[11:43:28.547] INFO (905279): Loading config file https://raw.githubusercontent.com/AcalaNetwork/chopsticks/master/configs/moonbeam.yml
```

Any clues?

**Comment by qiweiii** [comment]
`@acala-network/chopsticks@latest` is version 0.9.3

`npx @acala-network/chopsticks@0.9.4-6 xcm -r polkadot -p hydradx -p moonbeam` will work

**Comment by ermalkaleci** [comment]
@albertov19 use beta

**Comment by ermalkaleci** [comment]
<img width="984" alt="Screenshot 2023-12-07 at 12 31 03 PM" src="https://github.com/AcalaNetwork/chopsticks/assets/3055344/3eb8a262-dff1-45ac-8fb3-7eec31df5997">

**Comment by albertov19** [comment]
I wanted to reopen this until the fix is done in the smoldot thing

**Comment by ermalkaleci** [comment]
better open an issue on smoldot
