### ISSUE TITLE
Note preimage causing crash with Phala

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/chopsticks#583]
`yarn start --endpoint wss://api.phala.network/ws`
and 

`api.rpc('dev_setStorage', {
system: { account: [[['45R2pfjQUW2s9PQRHU48HQKLKHVMaDja7N3wpBtmF28UYDs2'], { providers: 1, data: { free: '100000000000000000000000'}}]]}
})` 

and use pjs apps to note a preimage and it crashed

```
file:///Users/xiliangchen/projects/acala/chopsticks/executor/dist/esm/chopsticks_executor.js:575
        var ret = new Error(getStringFromWasm0(arg0, arg1));
                  ^
Error: TypeError: Reflect.get called on non-object
    at imports.wbg.__wbindgen_error_new (file:///Users/xiliangchen/projects/acala/chopsticks/executor/dist/esm/chopsticks_executor.js:575:19)
    at wasm://wasm/00976396:wasm-function[705]:0x1293a0
    at wasm://wasm/00976396:wasm-function[93]:0x978a6
    at wasm://wasm/00976396:wasm-function[356]:0x10e5ed
    at wasm://wasm/00976396:wasm-function[945]:0x134d91
    at __wbg_adapter_46 (file:///Users/xiliangchen/projects/acala/chopsticks/executor/dist/esm/chopsticks_executor.js:375:10)
    at real (file:///Users/xiliangchen/projects/acala/chopsticks/executor/dist/esm/chopsticks_executor.js:359:22)
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
```

**Comment by ermalkaleci** [comment]
I tried but can't reproduce it

**Comment by xlc** [comment]
maybe I didn't build wasm
