### ISSUE TITLE
Abnormal Closure for Polkadot parachain fork on port `8000`

### ISSUE THREAD

**Issue by Chralt98** [AcalaNetwork/chopsticks#587]
Could you take a look at this issue? https://github.com/Moonsong-Labs/moonwall/issues/338

However, it might be a problem caused by moonwall.. But maybe you can help.

**Comment by xlc** [comment]
I am not familiar with the moonwall tool and the logs looks like from the client side and doesn't contain enough information for debugging. Would you be able to somehow get the logs from Chopsticks side? Also verbose logs can be enabled via `LOG_LEVEL=debug` or `trace` env.

**Comment by Chralt98** [comment]
Ok, much clearer now thanks Bryan.

Here are the logs and now I know how to proceed.

```csharp
[12:46:30.040] DEBUG (plugin/19898): Registered plugin CLI: decode-key
[12:46:30.061] DEBUG (plugin/19898): Registered plugin CLI: dry-run
[12:46:30.063] DEBUG (plugin/19898): Registered plugin CLI: follow-chain
[12:46:30.070] DEBUG (plugin/19898): Registered plugin CLI: run-block
[12:46:30.078] DEBUG (plugin/19898): Registered plugin CLI: try-runtime
[12:46:30.485] DEBUG (19898): Args
    endpoint: "wss://main.rpc.zeitgeist.pm/ws"
    buildBlockMode: 2
    db: {
      "datasource": {}
    }
    mockSignatureHost: true
    blockHash: "0x29861a163c368ef8ba6bde1aee6e5e343d26321c4ff00bd547d4c837e85af8c8"
Unable to map [u8; 32] to a lookup index
[12:46:33.019] DEBUG (ws/19898): Try starting on port 8000
[12:46:33.085] INFO (xcm/19898): Zeitgeist RPC listening on port 8000
[12:46:33.128] DEBUG (ws/19898): New connection
[12:46:33.219] DEBUG (ws/19898): Connection closed
[12:46:33.219] DEBUG (ws/19898): New connection
[12:46:33.438] DEBUG (ws/19898): New connection
[12:46:33.519] DEBUG (plugin/19898): Registered plugin set-storage RPC
[12:46:33.520] DEBUG (19898): dev_setStorage
    hash: "0x29861a163c368ef8ba6bde1aee6e5e343d26321c4ff00bd547d4c837e85af8c8"
    values: {
      "parachainSystem": {
        "authorizedUpgrade": "0x8ddc7dd6bc922210fdb4fe350399eb4824a75ed327d99a0737fab2c58641a8af"
      }
    }
[12:46:33.541] DEBUG (ws/19898): Connection closed
[12:46:33.541] DEBUG (ws/19898): New connection
[12:46:33.623] DEBUG (plugin/19898): Registered plugin new-block RPC
[12:46:33.950] INFO (block-builder/19898): Try building block #4,456,479
    number: 4456479
    extrinsicsCount: 0
    umpCount: 0
runtime                      ERROR: panicked at 'Block invalid, supplied author is not eligible.', /home/builder/cargo/git/checkouts/nimbus-f0ce2f53edf2630d/1c8ba39/pallets/author-inherent/src/lib.rs:133:13
[12:46:37.075] WARN (block-builder/19898): Failed to apply inherents {} Error: wasm `unreachable` instruction executed
/blockchain/block-builder.js:159
            throw new Error('Failed to apply inherents');
                  ^

Error: Failed to apply inherents
    at initNewBlock (/blockchain/block-builder.js:159:19)
    at async buildBlock (/blockchain/block-builder.js:264:33)
    at async TxPool.buildBlock (/blockchain/txpool.js:313:43)
    at async TxPool.buildBlockIfNeeded (/blockchain/txpool.js:295:9)

Node.js v20.10.0
```
