### ISSUE TITLE
instructions do not work

### ISSUE THREAD

**Issue by brenzi** [AcalaNetwork/chopsticks#63]
Tried the README examples without success

```
> yarn install
➤ YN0000: ┌ Resolution step
➤ YN0002: │ ts-node-dev@npm:2.0.0 [cb6f5] doesn't provide @types/node (pcc22c), requested by ts-node
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 3s 398ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs@npm:17.6.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:17.6.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zod@npm:3.19.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 34s 257ms
➤ YN0000: ┌ Link step
➤ YN0007: │ wasm-pack@npm:0.10.3 must be built because it never has been before or the last one failed
➤ YN0007: │ sqlite3@npm:5.1.2 [cb6f5] must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.15.12 must be built because it never has been before or the last one failed
➤ YN0007: │ bufferutil@npm:4.0.7 must be built because it never has been before or the last one failed
➤ YN0007: │ es5-ext@npm:0.10.62 must be built because it never has been before or the last one failed
➤ YN0007: │ utf-8-validate@npm:5.0.10 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 12s 142ms
➤ YN0000: Done with warnings in 49s 883ms

> yarn start dev --config=configs/kusama.yml
Error: Cannot find module '../executor/pkg'
Require stack:
- /home/abrenzikofer/chopsticks/src/executor.ts
- /home/abrenzikofer/chopsticks/src/blockchain/block.ts
- /home/abrenzikofer/chopsticks/src/blockchain/index.ts
- /home/abrenzikofer/chopsticks/src/index.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/abrenzikofer/chopsticks/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/abrenzikofer/chopsticks/src/executor.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (/home/abrenzikofer/chopsticks/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/home/abrenzikofer/chopsticks/node_modules/ts-node/src/index.ts:1621:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/abrenzikofer/chopsticks/src/executor.ts',
    '/home/abrenzikofer/chopsticks/src/blockchain/block.ts',
    '/home/abrenzikofer/chopsticks/src/blockchain/index.ts',
    '/home/abrenzikofer/chopsticks/src/index.ts'
  ]
}
```

**Comment by brenzi** [comment]
pardon, RTFM. will try again
