### ISSUE TITLE
moonbeam error of `allow-unresolved-imports`

### ISSUE THREAD

**Issue by zqhxuyuan** [AcalaNetwork/chopsticks#650]
after set [allow-unresolved-imports to true](https://github.com/AcalaNetwork/chopsticks/pull/649/files#diff-5dce46f19545e969ba94cbe8dd5303f38fa296dfb821a36ae6aeb469a42d17a8L3), I have this error:
```
npx @acala-network/chopsticks@latest xcm \
--r=polkadot.yml \
--p=moonbeam.yml \
--p=acala.yml
[12:14:44.842] INFO (72894): Loading config file https://raw.githubusercontent.com/AcalaNetwork/chopsticks/master/configs/moonbeam.yml
    app: "chopsticks"
panicked at 'called `Result::unwrap()` on an `Err` value: VirtualMachine(UnresolvedFunctionImport { function: "ext_panic_handler_abort_on_panic_version_1", module_name: "env" })', src/task.rs:131:6

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (/Users/zqh/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:750:19)
    at wasm://wasm/00974292:wasm-function[729]:0x12a598
    at wasm://wasm/00974292:wasm-function[891]:0x133f33
    at wasm://wasm/00974292:wasm-function[805]:0x12e6ee
    at wasm://wasm/00974292:wasm-function[104]:0xa8282
    at wasm://wasm/00974292:wasm-function[356]:0x10e402
    at wasm://wasm/00974292:wasm-function[942]:0x1347c5
    at __wbg_adapter_46 (/Users/zqh/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:410:10)
    at real (/Users/zqh/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:394:22)
    at node:internal/process/task_queues:140:7



node:internal/event_target:1006
  process.nextTick(() => { throw err; });
                           ^
Error [RuntimeError]: unreachable
    at wasm://wasm/00974292:wasm-function[729]:0x12a6c1
    at wasm://wasm/00974292:wasm-function[891]:0x133f33
    at wasm://wasm/00974292:wasm-function[805]:0x12e6ee
    at wasm://wasm/00974292:wasm-function[104]:0xa8282
    at wasm://wasm/00974292:wasm-function[356]:0x10e402
    at wasm://wasm/00974292:wasm-function[942]:0x1347c5
    at __wbg_adapter_46 (/Users/zqh/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:410:10)
    at real (/Users/zqh/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:394:22)
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:290:10)
    at [kOnMessage] (node:internal/worker:301:37)
    at MessagePort.<anonymous> (node:internal/worker:202:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:731:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v18.10.0
```

for moonbeam, maybe set it to false?

ref issue: https://github.com/AcalaNetwork/chopsticks/issues/575

**Comment by ermalkaleci** [comment]
#649 fixed

**Comment by ermalkaleci** [comment]
0.9.8-2 includes the fix
