### ISSUE TITLE
kusama example fails. js/apps can't connect

### ISSUE THREAD

**Issue by brenzi** [AcalaNetwork/chopsticks#66]
```
> yarn start dev --config=configs/kusama.yml
[12:06:18.867] INFO (6524): Args
    endpoint: "wss://kusama-rpc.dwellir.com"
    block: 15571512
    import-storage: {
      "System": {
        "Account": [
          [
            [
              "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
            ],
            {
              "data": {
                "free": "10000000000000000000"
              }
            }
          ]
        ]
      },
      "Council": {
        "Members": [
          "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
        ]
      },
      "PhragmenElection": {
        "Members": [
          {
            "who": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
            "stake": 1000000000000,
            "deposit": 1000000000000
          }
        ]
      },
      "TechnicalCommittee": {
        "Members": [
          "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
        ]
      },
      "TechnicalMembership": {
        "Members": [
          "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
        ]
      }
    }
    mock-signature-host: true
    db: "./db.sqlite"
    _: [
      "dev"
    ]
    config: "configs/kusama.yml"
    $0: "node_modules/ts-node/dist/bin.js"
    blockHash: "0x5c6d7556c1e0905f7ae6cce5b3ffa11b894727bb46cae724d27645a96b6deb9d"
[12:06:21.225] INFO (task/6524): Mock signature host enabled
```

`ws://localhost:8000` stays unresponsive, although

```
> netstat -tulpen
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 127.0.0.1:40783         0.0.0.0:*               LISTEN      1000       22887      5479/node
tcp6       0      0 :::8000                 :::*                    LISTEN      1000       20878      5933/node
```

**Comment by ermalkaleci** [comment]
not sure what's failing

**Comment by xlc** [comment]
does other network work for you?
can you add `LOG_LEVEL=trace` and provide logs?

**Comment by brenzi** [comment]
here's the trace:
```
[11:02:49.269] INFO (1159): Args
    endpoint: "wss://kusama-rpc.dwellir.com"
    block: 15571512
    import-storage: {
      "System": {
        "Account": [
          [
            [
              "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
            ],
            {
              "data": {
                "free": "10000000000000000000"
              }
            }
          ]
        ]
      },
      "Council": {
        "Members": [
          "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
        ]
      },
      "PhragmenElection": {
        "Members": [
          {
            "who": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
            "stake": 1000000000000,
            "deposit": 1000000000000
          }
        ]
      },
      "TechnicalCommittee": {
        "Members": [
          "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
        ]
      },
      "TechnicalMembership": {
        "Members": [
          "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
        ]
      }
    }
    mock-signature-host: true
    db: "./db.sqlite"
    _: [
      "dev"
    ]
    config: "configs/kusama.yml"
    $0: "node_modules/ts-node/dist/bin.js"
    blockHash: "0x5c6d7556c1e0905f7ae6cce5b3ffa11b894727bb46cae724d27645a96b6deb9d"
[11:02:52.445] INFO (task/1159): Mock signature host enabled
[11:02:52.446] DEBUG (ws/1159): Starting on port 8000
[11:02:52.448] DEBUG (ws/1159): Listening
    address: "::"
    family: "IPv6"
    port: 8000
[11:02:55.997] TRACE (1159): ImportStorage
    blockHash: "0x5c6d7556c1e0905f7ae6cce5b3ffa11b894727bb46cae724d27645a96b6deb9d"
    storage: {
      "System": {
        "Account": [
          [
            [
              "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
            ],
            {
              "data": {
                "free": "10000000000000000000"
              }
            }
          ]
        ]
      },
      "Council": {
        "Members": [
          "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
        ]
      },
      "PhragmenElection": {
        "Members": [
          {
            "who": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
            "stake": 1000000000000,
            "deposit": 1000000000000
          }
        ]
      },
      "TechnicalCommittee": {
        "Members": [
          "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
        ]
      },
      "TechnicalMembership": {
        "Members": [
          "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
        ]
      }
    }
```
I'm executing in WSL, but other node based services have worked in the past

**Comment by brenzi** [comment]
why is it only listening on IPv6?

**Comment by brenzi** [comment]
upon connection by js/apps, the trace shows:
```
[11:20:45.530] DEBUG (ws/1653): New connection
(node:1653) UnhandledPromiseRejectionWarning: TypeError: Object.hasOwn is not a function
    at WebSocket.<anonymous> (/home/abrenzikofer/chopsticks/src/server.ts:88:27)
    at WebSocket.emit (events.js:400:28)
    at WebSocket.emit (domain.js:475:12)
    at Receiver.receiverOnMessage (/home/abrenzikofer/chopsticks/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.emit (domain.js:475:12)
    at Receiver.dataMessage (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:83:10)
(node:1653) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:1653) UnhandledPromiseRejectionWarning: TypeError: Object.hasOwn is not a function
    at WebSocket.<anonymous> (/home/abrenzikofer/chopsticks/src/server.ts:88:27)
    at WebSocket.emit (events.js:400:28)
    at WebSocket.emit (domain.js:475:12)
    at Receiver.receiverOnMessage (/home/abrenzikofer/chopsticks/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.emit (domain.js:475:12)
    at Receiver.dataMessage (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:83:10)
(node:1653) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:1653) UnhandledPromiseRejectionWarning: TypeError: Object.hasOwn is not a function
    at WebSocket.<anonymous> (/home/abrenzikofer/chopsticks/src/server.ts:88:27)
    at WebSocket.emit (events.js:400:28)
    at WebSocket.emit (domain.js:475:12)
    at Receiver.receiverOnMessage (/home/abrenzikofer/chopsticks/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.emit (domain.js:475:12)
    at Receiver.dataMessage (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:83:10)
(node:1653) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:1653) UnhandledPromiseRejectionWarning: TypeError: Object.hasOwn is not a function
    at WebSocket.<anonymous> (/home/abrenzikofer/chopsticks/src/server.ts:88:27)
    at WebSocket.emit (events.js:400:28)
    at WebSocket.emit (domain.js:475:12)
    at Receiver.receiverOnMessage (/home/abrenzikofer/chopsticks/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.emit (domain.js:475:12)
    at Receiver.dataMessage (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:83:10)
(node:1653) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
(node:1653) UnhandledPromiseRejectionWarning: TypeError: Object.hasOwn is not a function
    at WebSocket.<anonymous> (/home/abrenzikofer/chopsticks/src/server.ts:88:27)
    at WebSocket.emit (events.js:400:28)
    at WebSocket.emit (domain.js:475:12)
    at Receiver.receiverOnMessage (/home/abrenzikofer/chopsticks/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.emit (domain.js:475:12)
    at Receiver.dataMessage (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:83:10)
(node:1653) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
(node:1653) UnhandledPromiseRejectionWarning: TypeError: Object.hasOwn is not a function
    at WebSocket.<anonymous> (/home/abrenzikofer/chopsticks/src/server.ts:88:27)
    at WebSocket.emit (events.js:400:28)
    at WebSocket.emit (domain.js:475:12)
    at Receiver.receiverOnMessage (/home/abrenzikofer/chopsticks/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.emit (domain.js:475:12)
    at Receiver.dataMessage (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/abrenzikofer/chopsticks/node_modules/ws/lib/receiver.js:83:10)
(node:1653) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
```

**Comment by ermalkaleci** [comment]
`TypeError: Object.hasOwn is not a function` your node version seems to be older than v16.9.0

**Comment by ermalkaleci** [comment]
should be fixed now

**Comment by brenzi** [comment]
fixed indeed. thx
