### ISSUE TITLE
Error when running the quick start start example

### ISSUE THREAD

**Issue by sebastianmontero** [AcalaNetwork/chopsticks#661]
I'm trying out chopsticks for the first time and when I try tu run the quick start example:
`npx @acala-network/chopsticks@latest \
--config=https://raw.githubusercontent.com/AcalaNetwork/chopsticks/master/configs/moonbeam.yml`

I'm getting the following error:
```
panicked at 'called `Result::unwrap()` on an `Err` value: VirtualMachine(UnresolvedFunctionImport { function: "ext_panic_handler_abort_on_panic_version_1", module_name: "env" })', src/task.rs:131:6

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (/home/sebastian/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:750:19)
    at wasm://wasm/00974292:wasm-function[729]:0x12a598
    at wasm://wasm/00974292:wasm-function[891]:0x133f33
    at wasm://wasm/00974292:wasm-function[805]:0x12e6ee
    at wasm://wasm/00974292:wasm-function[104]:0xa8282
    at wasm://wasm/00974292:wasm-function[356]:0x10e402
    at wasm://wasm/00974292:wasm-function[942]:0x1347c5
    at __wbg_adapter_46 (/home/sebastian/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:410:10)
    at real (/home/sebastian/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:394:22)
    at node:internal/process/task_queues:140:7



node:internal/event_target:1010
  process.nextTick(() => { throw err; });
                           ^
Error [RuntimeError]: unreachable
    at wasm://wasm/00974292:wasm-function[729]:0x12a6c1
    at wasm://wasm/00974292:wasm-function[891]:0x133f33
    at wasm://wasm/00974292:wasm-function[805]:0x12e6ee
    at wasm://wasm/00974292:wasm-function[104]:0xa8282
    at wasm://wasm/00974292:wasm-function[356]:0x10e402
    at wasm://wasm/00974292:wasm-function[942]:0x1347c5
    at __wbg_adapter_46 (/home/sebastian/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:410:10)
    at real (/home/sebastian/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:394:22)
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:290:10)
    at [kOnMessage] (node:internal/worker:301:37)
    at MessagePort.<anonymous> (node:internal/worker:202:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
```
Why might this be?

I'm using nodejs 18.15

**Comment by ermalkaleci** [comment]
https://github.com/AcalaNetwork/chopsticks/issues/658

**Comment by ermalkaleci** [comment]
use the latest beta
