### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: RuntimeVersion(RuntimeVersionDecode)

### ISSUE THREAD

**Issue by ntn-x2** [AcalaNetwork/chopsticks#666]
From the branch at: https://github.com/KILTprotocol/kilt-node/tree/aa/dip-improvements, and the runtime `dip-consumer-runtime-template`.

Full error:

```
[13:08:18.340] INFO: DIP consumer dev RPC listening on port 8000
    app: "chopsticks"
[13:08:18.340] INFO: Loading config file https://raw.githubusercontent.com/AcalaNetwork/chopsticks/master/configs/rococo.yml
    app: "chopsticks"
panicked at src/task.rs:131:6:
called `Result::unwrap()` on an `Err` value: RuntimeVersion(RuntimeVersionDecode)

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (/home/antonio/.npm/_npx/c1c4d257924715f9/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:748:19)
    at wasm://wasm/00966b66:wasm-function[701]:0x1269bf
    at wasm://wasm/00966b66:wasm-function[866]:0x130a13
    at wasm://wasm/00966b66:wasm-function[795]:0x12b783
    at wasm://wasm/00966b66:wasm-function[105]:0xa7664
    at wasm://wasm/00966b66:wasm-function[380]:0x10eb7c
    at wasm://wasm/00966b66:wasm-function[917]:0x1312f9
    at __wbg_adapter_48 (/home/antonio/.npm/_npx/c1c4d257924715f9/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:410:10)
    at real (/home/antonio/.npm/_npx/c1c4d257924715f9/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:394:22)
    at node:internal/process/task_queues:140:7


[13:08:19.250] INFO: Rococo RPC listening on port 8001
    app: "chopsticks"

node:internal/event_target:1033
  process.nextTick(() => { throw err; });
                           ^
Error [RuntimeError]: unreachable
    at wasm://wasm/00966b66:wasm-function[701]:0x126ad5
    at wasm://wasm/00966b66:wasm-function[866]:0x130a13
    at wasm://wasm/00966b66:wasm-function[795]:0x12b783
    at wasm://wasm/00966b66:wasm-function[105]:0xa7664
    at wasm://wasm/00966b66:wasm-function[380]:0x10eb7c
    at wasm://wasm/00966b66:wasm-function[917]:0x1312f9
    at __wbg_adapter_48 (/home/antonio/.npm/_npx/c1c4d257924715f9/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:410:10)
    at real (/home/antonio/.npm/_npx/c1c4d257924715f9/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:394:22)
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:300:10)
    at [kOnMessage] (node:internal/worker:311:37)
    at MessagePort.<anonymous> (node:internal/worker:212:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:757:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v18.18.2
```

Runtime is based on Polkadot 0.9.43, attached to a Rococo local also running 0.9.43. Is there a specific version of chopsticks I should use for this, or is the error due to something else?

**Comment by ermalkaleci** [comment]
https://github.com/AcalaNetwork/chopsticks/issues/663

**Comment by ntn-x2** [comment]
@ermalkaleci thanks for the prompt response! So I get that there is not a single source of error, but I have to try the different options tried in the issue you linked? Or do you want me to comment on that issue?

**Comment by ermalkaleci** [comment]
the above error is because of the wrong version

**Comment by ermalkaleci** [comment]
your runtime fails here https://github.com/smol-dot/smoldot/blob/210cc8bacecf5f3ea0057c80183cc9efe7f45f73/lib/src/executor/host/runtime_version.rs#L438

**Comment by ntn-x2** [comment]
Ok thank you. By wrong version I assume you mean the wrong chopsticks version? What is the latest version of chopstick that works with a runtime based on Substrate 1.0.0?

**Comment by ntn-x2** [comment]
I tried `state_version` with value `0`, `1`, and `5`, based on the linked issues, and they all returned the same error. The runtime is a template runtime, so I can change any value and restart the chain. What value should I put in there to make it work with chopsticks? Runtime is this: https://github.com/KILTprotocol/kilt-node/blob/develop/dip-template/runtimes/dip-consumer/src/lib.rs.

**Comment by ermalkaleci** [comment]
the previous issue is getting decode error because they have state_version: 5 which is invalid. I don't know what's your issue but smoldot fails to decode your runtime version. You will need to do some debugging. Also kilt seems to work with chopsticks, what endpoint are you trying to test?

**Comment by ermalkaleci** [comment]
upload the wasm here, I will give it a try

**Comment by ntn-x2** [comment]
https://drive.google.com/file/d/1-s9lnSNjSXslS6w8n2F0-h3GajRiOhLq

**Comment by ermalkaleci** [comment]
in your case it seems it can decode `runtimeVersion.apis`
