### ISSUE TITLE
Chopsticks XCM Error After Recent Update

### ISSUE THREAD

**Issue by wuzhong-papermoon** [AcalaNetwork/chopsticks#708]
Hi Chopsticks Team,

I'm writing to report an issue I've encountered after the recent update. When I run xcm commands using Chopsticks, I receive the following error message:
`Error: server.handleUpgrade() was called more than once with the same socket, possibly due to a misconfiguration`

I think the relayer chain might be attempting to open a duplicate port(suspecting port 8000/8001). I've verified that ports 8000 to 8005 are all available before execution.

Here's the command I used:
```
npx @acala-network/chopsticks@latest xcm \
--r="configs/polkadot.yml" \
--p="configs/moonbeam.yml" \
--p="configs/polkadot-asset-hub.yml"
```
Below is the complete error prompted:

```
Error: server.handleUpgrade() was called more than once with the same socket, possibly due to a misconfiguration
    at WebSocketServer.completeUpgrade (/Users/abc/.npm/_npx/81ad9c881cb83600/node_modules/ws/lib/websocket-server.js:366:13)
    at WebSocketServer.handleUpgrade (/Users/abc/.npm/_npx/81ad9c881cb83600/node_modules/ws/lib/websocket-server.js:343:10)
    at Server.upgrade (/Users/abc/.npm/_npx/81ad9c881cb83600/node_modules/ws/lib/websocket-server.js:119:16)
    at Server.emit (node:events:526:35)
    at Server.emit (node:domain:489:12)
    at onParserExecuteCommon (node:_http_server:915:14)
    at onParserExecute (node:_http_server:809:3)
```

Please let me know if you require any additional information to help troubleshoot this issue.
Hope this issue will be resolved soon. Cheers!

**Comment by ermalkaleci** [comment]
I've identified the issue. The workaround for now is to start each chain to a specified port
