### ISSUE TITLE
Error when trying to upgrade Polkadot runtime

### ISSUE THREAD

**Issue by NachoPal** [AcalaNetwork/chopsticks#710]
I am getting the following error when trying to run latests Polkadot's runtime upgrade because of [`init_state_migration::InitMigrate`](https://github.com/polkadot-fellows/runtimes/blob/main/relay/polkadot/src/lib.rs#L1870)

```
runtime::state-trie-migration DEBUG: [19993546] 🤖 running migrations on top of MigrationTask { top: To start, child: To start, dyn_top_items: 0, dyn_child_items: 0, dyn_size: 0, size: 0, top_items: 0, child_items: 0 } until MigrationLimits { size: 409600, item: 4800 }
runtime::state-trie-migration TRACE: [19993546] 🤖 migrated a top key, next_top_key = Some(BoundedVec([], 512))
runtime::state-trie-migration TRACE: [19993546] 🤖 migrated a top key, next_top_key = Some(BoundedVec([5, 149, 38, 117, 134, 181, 119, 68, 146, 120, 132, 245, 25, 235, 129, 1, 78, 123, 144, 18, 9, 107, 65, 196, 235, 58, 175, 148, 127, 110, 164, 41], 512))
runtime::state-trie-migration TRACE: [19993546] 🤖 migrated a top key, next_top_key = Some(BoundedVec([6, 222, 61, 138, 84, 210, 126, 68, 169, 213, 206, 24, 150, 24, 242, 45, 78, 123, 144, 18, 9, 107, 65, 196, 235, 58, 175, 148, 127, 110, 164, 41], 512))
runtime::state-trie-migration TRACE: [19993546] 🤖 migrated a top key, next_top_key = Some(BoundedVec([6, 222, 61, 138, 84, 210, 126, 68, 169, 213, 206, 24, 150, 24, 242, 45, 83, 180, 18, 59, 46, 24, 110, 7, 251, 123, 173, 93, 218, 95, 85, 192], 512))
runtime::state-trie-migration TRACE: [19993546] 🤖 migrated a top key, next_top_key = Some(BoundedVec([6, 222, 61, 138, 84, 210, 126, 68, 169, 213, 206, 24, 150, 24, 242, 45, 180, 180, 157, 149, 50, 13, 144, 33, 153, 76, 133, 15, 37, 184, 227, 133], 512))
panicked at /Users/nacho/Desktop/PARITY/Repos/chopsticks/vendor/smoldot/lib/src/executor/storage_diff.rs:207:13:
assertion failed: in_parent_next_key > key

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/executor/dist/esm/chopsticks_executor.js:801:19)
    at wasm://wasm/00b1e282:wasm-function[1108]:0x191195
    at wasm://wasm/00b1e282:wasm-function[1334]:0x19979c
    at wasm://wasm/00b1e282:wasm-function[1318]:0x1992e0
    at wasm://wasm/00b1e282:wasm-function[245]:0x10b484
    at wasm://wasm/00b1e282:wasm-function[115]:0xba794
    at wasm://wasm/00b1e282:wasm-function[632]:0x16b359
    at wasm://wasm/00b1e282:wasm-function[1476]:0x19aeb1
    at __wbg_adapter_48 (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/executor/dist/esm/chopsticks_executor.js:384:10)
    at real (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/executor/dist/esm/chopsticks_executor.js:366:22)



node:internal/event_target:1096
  process.nextTick(() => { throw err; });
                           ^
Error [RuntimeError]: unreachable
    at wasm://wasm/00b1e282:wasm-function[1108]:0x1912ab
    at wasm://wasm/00b1e282:wasm-function[1334]:0x19979c
    at wasm://wasm/00b1e282:wasm-function[1318]:0x1992e0
    at wasm://wasm/00b1e282:wasm-function[245]:0x10b484
    at wasm://wasm/00b1e282:wasm-function[115]:0xba794
    at wasm://wasm/00b1e282:wasm-function[632]:0x16b359
    at wasm://wasm/00b1e282:wasm-function[1476]:0x19aeb1
    at __wbg_adapter_48 (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/executor/dist/esm/chopsticks_executor.js:384:10)
    at real (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/executor/dist/esm/chopsticks_executor.js:366:22)
    at node:internal/process/task_queues:140:7
```

probably a `smoldot` issue

**Comment by ermalkaleci** [comment]
@NachoPal  Can you provide steps to reproduce? I tried runtime from https://github.com/polkadot-fellows/runtimes/releases/tag/v1.1.3 and it seems to work fine. What am I missing?
