### ISSUE TITLE
Method not found state_getStorageAt

### ISSUE THREAD

**Issue by Tbaut** [AcalaNetwork/chopsticks#718]
Hello there, I'm running into this issue when I'm using the latest version of subsquid indexer against Chopsticks v0.9.13
I'm forking Kusama, using this config: https://github.com/ChainSafe/Multix/blob/tbaut-bump-subsquid/chopsticks-config.yml

Here is the error:
```
[00:31:34.428] INFO: Kusama RPC listening on port 8000
    app: "chopsticks"
[00:32:18.199] WARN (rpc): Method not found state_getStorageAt
    app: "chopsticks"
[00:32:18.200] INFO (ws): Error handling request: 'ResponseError: Method not found: state_getStorageAt
    at /home/thib/.npm/_npx/fffae069f13e874a/node_modules/@acala-network/chopsticks/dist/cjs/rpc/index.js:39:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async processRequest (/home/thib/.npm/_npx/fffae069f13e874a/node_modules/@acala-network/chopsticks/dist/cjs/server.js:211:30)
    at async WebSocket.<anonymous> (/home/thib/.npm/_npx/fffae069f13e874a/node_modules/@acala-network/chopsticks/dist/cjs/server.js:273:30)'
```

In case this helps, the trace of the calls with the exact `state_getStorageAt` is the following:
```
00:37:41 DEBUG sqd:processor:rpc rpc call
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 7
                                 rpcMethod: state_getStorageAt
                                 rpcParams: ["0x26aa394eea5630e07c48ae0c9558cef780d41e5e16056765bc8461851072c9d7","0x6b6d12100936161daa7e194db94cd7c24e0d732ce9fcb120a85f117c8ecf2185"]
00:37:41 DEBUG sqd:processor:rpc rpc call
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 8
                                 rpcMethod: state_getRuntimeVersion
                                 rpcParams: ["0x6b6d12100936161daa7e194db94cd7c24e0d732ce9fcb120a85f117c8ecf2185"]
00:37:41 DEBUG sqd:processor:rpc rpc send
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 7
00:37:41 DEBUG sqd:processor:rpc rpc send
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 8
00:37:41 DEBUG sqd:processor:rpc rpc response
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 7
                                 rpcMethod: state_getStorageAt
                                 rpcParams: ["0x26aa394eea5630e07c48ae0c9558cef780d41e5e16056765bc8461851072c9d7","0x6b6d12100936161daa7e194db94cd7c24e0d732ce9fcb120a85f117c8ecf2185"]
                                 rpcResponse: {"id":7,"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found: state_getStorageAt"}}
00:37:41 DEBUG sqd:processor:rpc rpc response
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 8
                                 rpcMethod: state_getRuntimeVersion
                                 rpcParams: ["0x6b6d12100936161daa7e194db94cd7c24e0d732ce9fcb120a85f117c8ecf2185"]
                                 rpcResponse: {"id":8,"jsonrpc":"2.0","result":{"specName":"kusama","implName":"parity-kusama","authoringVersion":2,"specVersion":1001003,"implVersion":0,"apis":[["0xdf6acb689907609b",4],["0x37e397fc7c91f5e4",2],["0x40fe3ad401f8959a",6],["0xd2bc9897eed08f15",3],["0xf78b278be53f454c",2],["0xaf2c0297a23e6d3d",7],["0x49eaaf1b548a0cb0",3],["0x91d5df18b0d2cf58",2],["0x2a5e924655399e60",1],["0xed99c5acb25eedf5",3],["0xcbca25e39f142387",2],["0x687ad44ad37f03c2",1],["0xab3c0572291feb8b",1],["0xbc9d89904f5b923f",1],["0x37c8bb1350a9a2a8",4],["0xf3ff14d5ab527059",3],["0x17a6bc0d0062aeb3",1],["0x18ef58a3b67ba770",1],["0xfbc577b9d747efd6",1]],"transactionVersion":25,"stateVersion":1}}
00:37:41 FATAL sqd:processor Error: Failed to fetch block 22568473#6b6d1

```

**Comment by xlc** [comment]
can you give this a quick try? https://github.com/AcalaNetwork/chopsticks/pull/719
