### ISSUE TITLE
cant launch Picasso parachain using chopsticks

### ISSUE THREAD

**Issue by kkast** [AcalaNetwork/chopsticks#786]
Hello, we have been using chopsticks to test runtime upgrades for picasso chain. Since the change of kusama to coretime we start getting this error for both commands despite trying different versions of chopsticks including the latest one.

npx @acala-network/chopsticks@latest xcm -r kusama -p picasso-kusama  
npx @acala-network/chopsticks@latest -c picasso-kusama

[01:41:56.187] INFO (block-builder): Picasso building #5,180,886
    app: "chopsticks"
    number: 5180886
    extrinsics: [
      "0x45028400d43593c715fdd31c61141abd…77cd4b77b846f2a5f07c070010a5d4e8"
    ]
    umpCount: 0
                     runtime  ERROR: panicked at 'assertion failed: ingress_channels.binary_search_by_key(sender, |&(s, _)| s).is_ok()', /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vendor-cargo-deps/442dab8d7f9b15bfa988b8093ff666a268943675b515d76043b56d3b8a60e964/cumulus-pallet-parachain-system-0.1.0/src/lib.rs:895:13
[01:41:57.732] WARN (block-builder): Failed to apply inherents {} Error: wasm `unreachable` instruction executed
    app: "chopsticks"
/home/user/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-core/dist/cjs/blockchain/block-builder.js:213
            throw new Error('Failed to apply inherents');
                  ^

Error: Failed to apply inherents
    at initNewBlock (/home/user/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-core/dist/cjs/blockchain/block-builder.js:213:19)
    at async buildBlock (/home/user/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-core/dist/cjs/blockchain/block-builder.js:320:44)
    at async TxPool.buildBlock (/home/user/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-core/dist/cjs/blockchain/txpool.js:340:43)
    at async TxPool.buildBlockIfNeeded (/home/user/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-core/dist/cjs/blockchain/txpool.js:324:9)
    
    could you please tell us what is causing this to fail?

**Comment by xlc** [comment]
what version of polkadot sdk is picasso using?

**Comment by kkast** [comment]
0.9.43
