### ISSUE TITLE
MODULE_NOT_FOUND error on running chopsticks in powershell 

### ISSUE THREAD

**Issue by JaromirProchazka** [AcalaNetwork/chopsticks#795]
Hi, I have a problem with running Chopsticks. I'm trying to run it on windows 11 PowerShell, it throws this error:

```
> npx @acala-network/chopsticks@latest -c acala
node:internal/modules/cjs/loader:1140
  const err = new Error(message);
              ^

Error: Cannot find module '/C:/Users/jarom/AppData/Local/npm-cache/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks/dist/cjs/plugins/decode-key/index.js'
Require stack:
- C:\Users\jarom\AppData\Local\npm-cache\_npx\81ad9c881cb83600\node_modules\@acala-network\chopsticks\dist\cjs\plugins\index.js
- C:\Users\jarom\AppData\Local\npm-cache\_npx\81ad9c881cb83600\node_modules\@acala-network\chopsticks\dist\cjs\cli.js
- C:\Users\jarom\AppData\Local\npm-cache\_npx\81ad9c881cb83600\node_modules\@acala-network\chopsticks\chopsticks.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at C:\Users\jarom\AppData\Local\npm-cache\_npx\81ad9c881cb83600\node_modules\@acala-network\chopsticks\dist\cjs\plugins\index.js:127:116
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async pluginExtendCli (C:\Users\jarom\AppData\Local\npm-cache\_npx\81ad9c881cb83600\node_modules\@acala-network\chopsticks\dist\cjs\plugins\index.js:127:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\jarom\\AppData\\Local\\npm-cache\\_npx\\81ad9c881cb83600\\node_modules\\@acala-network\\chopsticks\\dist\\cjs\\plugins\\index.js',
    'C:\\Users\\jarom\\AppData\\Local\\npm-cache\\_npx\\81ad9c881cb83600\\node_modules\\@acala-network\\chopsticks\\dist\\cjs\\cli.js',
    'C:\\Users\\jarom\\AppData\\Local\\npm-cache\\_npx\\81ad9c881cb83600\\node_modules\\@acala-network\\chopsticks\\chopsticks.cjs'
  ]
}

Node.js v18.20.3
```
I use this npm, npx version: `10.7.0`, 

however on `wsl`, it works.

**Comment by xlc** [comment]
No idea about this one as we are not using Windows but if it works with wsl then I guess keep using it?

**Comment by muddlebee** [comment]
@xlc I'm using this issue on windows as well
