### ISSUE TITLE
Error When Testing  Async Backing Enabling Runtime Upgrade 

### ISSUE THREAD

**Issue by Mihajlo-Pavlovic** [AcalaNetwork/chopsticks#806]
We are experiencing an error when trying to test the runtime upgrade which enables syncing on NeuroWeb Testnet.
We get this log on transaction after executing enactAuthorizedUpgrade:
```
[18:25:56.542] INFO (block-builder): NeuroWeb Testnet building #4,302,785
    app: "chopsticks"
    number: 4302785
    extrinsics: [
      "0x410284da2004a17a90220dba4b1e3c13…77cd4b77b846f2a5f07c070010a5d4e8"
    ]
    umpCount: 0
                     runtime  ERROR: panicked at /root/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/8c8edac/substrate/frame/aura/src/lib.rs:398:9:
assertion `left == right` failed: Timestamp slot must match `CurrentSlot`
  left: Slot(143688101)
 right: Slot(287376202)
[18:25:58.828] WARN (block-builder): Failed to apply inherents {} Error: wasm `unreachable` instruction executed
    app: "chopsticks"
/Users/mihajlopavlovic/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-core/dist/cjs/blockchain/block-builder.js:214
            throw new Error('Failed to apply inherents');
                  ^

Error: Failed to apply inherents
    at initNewBlock (/Users/mihajlopavlovic/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-core/dist/cjs/blockchain/block-builder.js:214:19)
    at async buildBlock (/Users/mihajlopavlovic/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-core/dist/cjs/blockchain/block-builder.js:321:44)
    at async TxPool.buildBlock (/Users/mihajlopavlovic/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-core/dist/cjs/blockchain/txpool.js:340:43)
    at async TxPool.buildBlockIfNeeded (/Users/mihajlopavlovic/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-core/dist/cjs/blockchain/txpool.js:324:9)
```
We are using polkadot-v1.11.0 and starting chopsticks with latest tag: ``` npx @acala-network/chopsticks@latest -c neuroweb-testnet```

This is the same error as issue #730 which is now closed.

**Comment by Mihajlo-Pavlovic** [comment]
It looks connected to this issue https://github.com/paritytech/polkadot-sdk/pull/3211, do chopsticks have this fix?

**Comment by ermalkaleci** [comment]
If you're testing the transition to async backing then it's not supported

**Comment by ermalkaleci** [comment]
you should try zombienet to test this transition because it depends purely on the client and you need to test your client can do it

**Comment by ermalkaleci** [comment]
@Mihajlo-Pavlovic this [PR](https://github.com/AcalaNetwork/chopsticks/pull/809) will add support
