### ISSUE TITLE
Support `archive_unstable_hashByHeight`

### ISSUE THREAD

**Issue by Tbaut** [AcalaNetwork/chopsticks#852]
hello there,
I'm using with papi the `archive_unstable_hashByHeight` because it's the only way to get a block hash from a block number. It used to be possible with pjs using `api.rpc.getBlockHash(number)`, and this was working well with Chopstick too.. but it's not the case any more.

Is there any way you can support this? Also I'm actually requesting a block height that has been seen by smoldot, so this block should be found easily.

Here's the error stack

> ERROR (ws): Error handling request: 'ResponseError: Method not found: archive_unstable_hashByHeight
[0]     at /home/thib/.npm/_npx/1063adea9feffe0e/node_modules/@acala-network/chopsticks/dist/cjs/rpc/index.js:39:19
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0]     at async processRequest (/home/thib/.npm/_npx/1063adea9feffe0e/node_modules/@acala-network/chopsticks/dist/cjs/server.js:225:30)
[0]     at async WebSocket.<anonymous> (/home/thib/.npm/_npx/1063adea9feffe0e/node_modules/@acala-network/chopsticks/dist/cjs/server.js:287:30)'
[0]     app: "chopsticks"

**Comment by ermalkaleci** [comment]
`archive_unstable_hashByHeight` has never existed on Chopsticks RPC. This is just an alias of getBlockHash and has nothing to do with smoldot. If you can please add this alias and make a PR

**Comment by Tbaut** [comment]
Thanks for the pointer, I have no idea what I'm talking about indeed! I'll check how to make aliases and make a pr ;)
