### ISSUE TITLE
Missing validationData when producing block

### ISSUE THREAD

**Issue by crystalin** [AcalaNetwork/chopsticks#92]
I've tried chopstick with Moonriver and it is not able to produce a block after sending a Tx:
`yarn start dev --endpoint=wss://moonriver.kaki.dev`

```
[15:10:29.155] INFO (txpool/4523): Building block
    hash: "0x6d31aa900f8334cbb623ab538ee633337bb7c2e3b4a1340c4f76678ddbc366d7"
    number: 3202514
    extrinsicsCount: 1
    tempHash: "0x5d42540000000000000000000000000000000000000000000000000000000000"
    timeValue: 1671199810076
    expectedSlot: 835599905038
/home/hello/projects/chopsticks/src/blockchain/inherents.ts:123
        extrinsic.validationData.relayParentStorageRoot as HexString,
                                 ^
TypeError: Cannot read properties of undefined (reading 'relayParentStorageRoot')
    at SetValidationData.createInherents (/home/hello/projects/chopsticks/src/blockchain/inherents.ts:123:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async InherentProviders.createInherents (/home/hello/projects/chopsticks/src/blockchain/inherents.ts:71:19)
    at async TxPool.#buildBlock (/home/hello/projects/chopsticks/src/blockchain/txpool.ts:125:23)
    at async TxPool.buildBlock (/home/hello/projects/chopsticks/src/blockchain/txpool.ts:62:5)
```

**Comment by crystalin** [comment]
This is due because the validationData expectedIndex is hardcoded to 1 but is currently `0` on Moonriver. We should have a way to customize it in the configuration.
When changing it howerver I get this error:

```
/home/hello/projects/chopsticks/src/blockchain/block.ts:257
            reject(new ResponseError(1, r.Error))
                   ^
ResponseError: Error while executing Wasm VM: Trap: Unreachable
"panicked at 'Mandatory randomness inherent not included; InherentIncluded storage item is empty', /build/pallets/randomness/src/lib.rs:305:13"
    at Object.callback (/home/hello/projects/chopsticks/src/blockchain/block.ts:257:20)
    at exec_taskResult (/home/hello/projects/chopsticks/src/rpc/exec.ts:44:44)
    at /home/hello/projects/chopsticks/src/rpc/index.ts:23:12
    at WebSocket.<anonymous> (/home/hello/projects/chopsticks/src/server.ts:110:28)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnMessage (/home/hello/projects/chopsticks/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.emit (node:domain:489:12)
    at Receiver.dataMessage (/home/hello/projects/chopsticks/node_modules/ws/lib/receiver.js:528:14) {
  code: 1
}
```

This is because we have an addition inherent for Randomness. Not sure where this should be added.

**Comment by ermalkaleci** [comment]
we can definitely decode and find validation_data without the need of an index
